### ISSUE TITLE
additional database columns

### ISSUE THREAD

**Issue by mattlub** [FACN1/city-guide#56]
potential extra db columns for nuggets:

1) date_added?
would be automatic and I feel we may as well store this data

2) expiry_date?
would be an optional extra in the form
may be useful if people want to post more temporary things like events

thoughts? @Karyum @Suuuuha @HilbertSpitzer

**Comment by Karyum** [comment]
1. does the user want to see the date that the nugget was added ?? cause i feel like the user only need to see the information about a certain landmark, i feel like the date added column would be more used by us the developers.

2. yeah the expiry date for events is great but we need to find a way so that users wouldn't abuse it (e.g: event that is going on forever and the user keeps making the expiry date longer to use it as advertisement for his place)

**Comment by mattlub** [comment]
Decision:
1) yes, add it
2) leave it for now
